import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import 'analytics_service.dart';
import '../models/habit_model.dart';

class PdfService {
  static Future<File> generateLifeResumePDF(AnalyticsData data, User? user) async {
    final pdf = pw.Document();

    final joinDate = user?.metadata.creationTime ?? DateTime(2026, 1, 1);
    final formattedJoinDate = DateFormat('MMMM d, yyyy').format(joinDate);
    final displayName = user?.displayName ?? 'Growth Enthusiast';

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("LifeProgreX - Life Resume", 
                  style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurple)),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Name: $displayName", style: const pw.TextStyle(fontSize: 18)),
              pw.Text("Member Since: $formattedJoinDate", style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
              pw.SizedBox(height: 30),
              
              pw.Header(level: 1, text: "This Month's Impact", textStyle: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _buildStatItem("Total Habits", data.habitsCompleted.toString()),
                  _buildStatItem("Reading", "${(data.readingMinutes / 60).toStringAsFixed(1)}h"),
                  _buildStatItem("Workouts", data.workoutSessions.toString()),
                  _buildStatItem("Learning", "${(data.learningMinutes / 60).toStringAsFixed(1)}h"),
                ]
              ),
              
              pw.SizedBox(height: 40),
              pw.Header(level: 1, text: "Life Skills Mastery", textStyle: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              _buildSkillItem("Consistency", (data.lifeScore * 100).toInt()),
              _buildSkillItem("Self-Discipline", ((data.lifeScore + data.averageMood / 10) / 2 * 100).toInt().clamp(0, 100)),
              _buildSkillItem("Mindfulness", (data.averageMood * 10).toInt().clamp(0, 100)),
              _buildSkillItem("Time Management", (data.categoryStats[HabitCategory.career]?['progress']?.toDouble() ?? 0.8 * 100).toInt()),
              _buildSkillItem("Goal Setting", (data.totalGoals / 10 * 100).toInt().clamp(0, 100)),

              pw.Spacer(),
              pw.Divider(color: PdfColors.grey400),
              pw.SizedBox(height: 5),
              pw.Center(
                child: pw.Text("Generated by LifeProgreX", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/LifeResume_$formattedJoinDate.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildStatItem(String label, String value) {
    return pw.Container(
      width: 100,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(value, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurpleAccent)),
          pw.SizedBox(height: 5),
          pw.Text(label, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey800)),
        ]
      )
    );
  }

  static pw.Widget _buildSkillItem(String name, int percent) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(name, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.Text("$percent%", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurple)),
        ]
      )
    );
  }
  
  static Future<void> shareLifeResumePDF(AnalyticsData data, User? user) async {
    final file = await generateLifeResumePDF(data, user);
    await Share.shareXFiles([XFile(file.path)], text: 'Check out my Life Resume on LifeProgreX!');
  }

  static Future<String> downloadLifeResumePDF(AnalyticsData data, User? user) async {
    final file = await generateLifeResumePDF(data, user);
    
    Directory? outDir;
    
    // Attempt to get the standard Downloads directory (works on Android)
    if (Platform.isAndroid) {
      try {
        outDir = await getDownloadsDirectory();
      } catch (e) {
        // Fallback if permission or directory access fails
      }
    }
    
    // Fallback to Documents directory (Standard for iOS Files app visibility)
    outDir ??= await getApplicationDocumentsDirectory();
    
    final savedFile = File('${outDir.path}/LifeResume_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await savedFile.writeAsBytes(await file.readAsBytes());
    return savedFile.path;
  }
}
